### ISSUE TITLE
Documentation request: Installation instructions

### ISSUE THREAD

**Issue by brandonzylstra** [fabiospampinato/noty#1]
It's not clear whether someone who simply wants to *use* Noty must install it the same way as someone who wants to modify the code:

```
git clone https://github.com/fabiospampinato/noty.git
npm install
npm run dev
```

Is there a more convenient way?  Such as `brew install noty`, or even `npm install -g noty`?

**Comment by fabiospampinato** [comment]
You can download a specific `.dmg` from GitHub's [releases](https://github.com/fabiospampinato/noty/releases) page.
