### ISSUE TITLE
Mixed styles

### ISSUE THREAD

**Issue by Li-An** [fabiospampinato/noty#11]
Hello, it seems it’s impossible to mix like done todo entry and bold content.

**Comment by fabiospampinato** [comment]
Yeah currently the syntax highlighting isn't great. Noty will be deprecated in favor of [Notable](https://github.com/notable/notable) in the near-ish future though.

**Comment by fabiospampinato** [comment]
This app is now deprecated, you should use [Notable](https://notable.md) instead, which is a much better note-taking app overall, its zen mode can replace Noty's UI pretty effectively and it is very actively developed.

Notable fixes this problem as well.
