### ISSUE TITLE
Mac style on Windows

### ISSUE THREAD

**Issue by JamesDAdams** [fabiospampinato/noty#12]
Hi,

first your software is very cool 👍 

but the style on windows is not borderless like on mac...
It's possible to add a borderless mod please ?

![image](https://user-images.githubusercontent.com/20860324/67074711-f08b8600-f189-11e9-9523-39525583b1f5.png)

**Comment by fabiospampinato** [comment]
This mostly comes down to Windows being crap, but there are ways around it.

This repo will soon be marked as archived though, in favor of [Notable](https://github.com/notable/notable), which will replace it.

**Comment by fabiospampinato** [comment]
This app is now deprecated, you should use [Notable](https://notable.md) instead, which is a much better note-taking app overall, its zen mode can replace Noty's UI pretty effectively and it is very actively developed.
