### ISSUE TITLE
Configurable configuration location

### ISSUE THREAD

**Issue by dcsan** [fabiospampinato/noty#3]
I like having TODO notes in a separate popup app, this is neat!

but is there a way to commit the files to source repo / dropbox etc?
Ideally i'd like to just be able to open / close the config file from a location on disc that I would set...

thanks for releasing this!

**Comment by fabiospampinato** [comment]
Currently it's not possible to do this via the app.

But you could set up a script that copies the file from Dropbox to where Noty expects it to be, and vice versa, when it changes. I'm personally just copying the configuration file periodically to Dropbox just to have it available from the phone in case I need to read it.

**Comment by dcsan** [comment]
ok thanks for reply. I use the same todo across work and home so... i guess I could have a watcher script / cron running but it seems a bit overkill for one tiny file...

**Comment by fabiospampinato** [comment]
Yeah sure, ideally Noty should ask where its configuration file should be saved, so that one could put it inside Dropbox and have it synchronized.

I'll actually have to code something similar for another app I'm working on, maybe then I'll port back this feature to Noty.

**Comment by Li-An** [comment]
Hello, no news about this feature (could be cool for Nextcloud)?

**Comment by fabiospampinato** [comment]
No news, but Noty will be deprecated in favor of [Notable](https://github.com/notable/notable) soon, which has this capability already.

**Comment by fabiospampinato** [comment]
This app is now deprecated, you should use [Notable](https://notable.md) instead, which is a much better note-taking app overall, its zen mode can replace Noty's UI pretty effectively and it is very actively developed.

Notable already supports this basically.
