### ISSUE TITLE
Creating new note with no windows open results in error

### ISSUE THREAD

**Issue by ghost** [fabiospampinato/noty#6]
`Cmd/Ctrl + N` works when there is already a note open, but when the application is open without any windows creating a new note results in error every time.

![image](https://user-images.githubusercontent.com/25064614/51073879-5d3d9580-16cb-11e9-80f3-96cba84efd9b.png)

**Comment by fabiospampinato** [comment]
This app is now deprecated, you should use [Notable](https://notable.md) instead, which is a much better note-taking app overall, its zen mode can replace Noty's UI pretty effectively and it is very actively developed.
