### ISSUE TITLE
Feature Request: Follow Spaces & Float, Styles

### ISSUE THREAD

**Issue by karkraeg** [fabiospampinato/noty#7]
Hi!

Would be great if Noty would follow Spaces and stay on top of all Windows like [ScreenFloat](https://www.screenfloatapp.com/ScreenFloat_-_Make_your_Shots_fly/ScreenFloat_-_Make_your_Shots_fly%21.html) 

Also styling via CSS would be awesome 😊

Great Work!

**Comment by fabiospampinato** [comment]
Isn't Window -> Float on top enough? If it's not I'm afraid regular windows like Noty's can't float on top of full-screen apps like that.

> Also styling via CSS would be awesome 😊

Can you open a separate issue about this?

**Comment by karkraeg** [comment]
Great, hadn’t seen floating in the Window menu. Are you considerung following spaces?

CSS Styling: https://github.com/fabiospampinato/noty/issues/8

**Comment by fabiospampinato** [comment]
> Are you considerung following spaces?

1. Put noty on the dock
2. Right click it
3. Options -> All Desktop

But this doesn't work with full-screen apps and as I said I don't think it can be implemented.

**Comment by karkraeg** [comment]
Thanks! Also didn’t know that this was a thing…

**Comment by karkraeg** [comment]
For anyone else wondering: both options are not persistent after reopening the app 😉

**Comment by fabiospampinato** [comment]
We are not preserving any state, but `Options -> All Desktop` should be preserved, at least it is for me 🤔
