### ISSUE TITLE
CSS Styling

### ISSUE THREAD

**Issue by karkraeg** [fabiospampinato/noty#8]
Styling via CSS would be awesome. Put a `.noty` CSS file in the Homefolder and document the CSS selectors to use perhaps?

**Comment by fabiospampinato** [comment]
I'm going to implement something similar to [Notable](https://github.com/fabiospampinato/notable), perhaps it could be backported to Noty also.

**Comment by fabiospampinato** [comment]
I'm going to implement something similar to [Notable](https://github.com/fabiospampinato/notable), perhaps it could be backported to Noty also.

**Comment by fabiospampinato** [comment]
This app is now deprecated, you should use [Notable](https://notable.md) instead, which is a much better note-taking app overall, its zen mode can replace Noty's UI pretty effectively and it is very actively developed.
